# Generated by Django 5.1.4 on 2024-12-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="video_url",
            field=models.URLField(default=1, verbose_name="Ссылка на видео"),
            preserve_default=False,
        ),
    ]
